### ISSUE TITLE
Error when trying the create jaspr project command.

### ISSUE THREAD

**Issue by hippedorange22** [schultek/jaspr#10]
`C:\Users\saifk\AppData\Local\Pub\Cache\bin>jaspr create jasp_web_app
Creating jasp_web_app using template web-simple...

  .gitignore
  analysis_options.yaml
  CHANGELOG.md
  pubspec.yaml
  README.md
  web\index.html
  web\main.dart
  web\styles.css

  lib/app.dart
  lib/app.dart

Resolving dependencies...
Null check operator used on a null value
package:pub/src/entrypoint.dart 157:60                           Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 100:21                           Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 97:42                            Entrypoint.lockFile
package:pub/src/entrypoint.dart 286:21                           Entrypoint.acquireDependencies.<fn>
package:pub/src/entrypoint.dart 280:68                           Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                                  progress
package:pub/src/entrypoint.dart 280:26                           Entrypoint.acquireDependencies
package:pub/src/command/get.dart 52:22                           GetCommand.runProtected
package:pub/src/command.dart 183:45                              PubCommand.run.<fn>
package:pub/src/command.dart 183:33                              PubCommand.run.<fn>
dart:async                                                       new Future.sync
package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
dart:async                                                       runZonedGuarded
package:pub/src/utils.dart 126:5                                 captureErrors
package:pub/src/command.dart 183:13                              PubCommand.run
package:args/command_runner.dart 209:27                          CommandRunner.runCommand
package:dartdev/dartdev.dart 231:30                              DartdevRunner.runCommand
package:args/command_runner.dart 119:25                          CommandRunner.run.<fn>
dart:async                                                       new Future.sync
package:args/command_runner.dart 119:14                          CommandRunner.run
package:dartdev/dartdev.dart 66:29                               runDartdev
C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    C:\Users\saifk\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
Null check operator used on a null value
#0      Entrypoint.lockFilePath (package:pub/src/entrypoint.dart:157:60)
#1      dumpTranscriptToFile (package:pub/src/log.dart:375:50)
#2      PubCommand.run (package:pub/src/command.dart:225:13)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#4      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:18)
<asynchronous suspension>
#5      runDartdev (package:dartdev/dartdev.dart:66:16)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>`

**Comment by schultek** [comment]
This seems to be an issue with running `dart pub get`. What happens if you run it manually? What version of dart and jaspr are you using?

**Comment by schultek** [comment]
The jaspr project was still generated right?

**Comment by schultek** [comment]
Can you try with `jaspr serve -v`and show the output.

**Comment by schultek** [comment]
Should be fixed in jaspr@0.1.5
