### ISSUE TITLE
Could not find an option named "no-ssr"

### ISSUE THREAD

**Issue by JannieT** [schultek/jaspr#107]
**Description**

Following the documentation for creating a static site, I run into the following error message:

> Could not find an option named "no-ssr"

**Steps to reproduce**

```
jaspr create -t client policy
cd policy
jaspr serve --no-ssr
```

jaspr version 0.8.0

----

What a cool project this is! Só excited to have discovered it.

**Comment by JannieT** [comment]
Oops! Found in the [0.7..0 release notes](https://github.com/schultek/jaspr/releases/tag/jaspr-v0.7.0) that the flag has moved to the pubspec.yaml file.

**Comment by schultek** [comment]
Hi, where in the docs is this? I need to update them. 😊
