### ISSUE TITLE
getting unhandled exception when running dart run  jaspr serve

### ISSUE THREAD

**Issue by dileep9490** [schultek/jaspr#11]
here's the output :
![Screenshot 2022-06-19 093744](https://user-images.githubusercontent.com/63330310/174465433-a4c55987-fd5f-4a32-9254-3ba24b98bb8c.png)

**Comment by schultek** [comment]
Are you on windows? 
Make sure you have `webdev: 2.7.7` as a dev dependency in your project.

**Comment by dileep9490** [comment]
I'm still getting the error after adding the dependency. 
I'm using the first project from jasprpad.

**Comment by schultek** [comment]
Do you have webdec activated globally? 
`pub global list`

I yes can you try and deactivate it.

**Comment by dileep9490** [comment]
I have it activated globally
![Screenshot 2022-06-19 191653](https://user-images.githubusercontent.com/63330310/174484258-19926f2f-72fa-4167-9c55-cd52cacf6125.png)
I tried to deactivate and activate it again still the error persists

**Comment by schultek** [comment]
Ok I will do a fix in a new version, It should work when you deactivate it globally for now.

**Comment by schultek** [comment]
Fixed in `jaspr@0.1.5`
