### ISSUE TITLE
Jaspr examples are outdated and mostly undocumented

### ISSUE THREAD

**Issue by dkbast** [schultek/jaspr#120]
**Description**

4 out of 5 of the ./examples are outdated (using older than current versions of jaspr):
https://github.com/schultek/jaspr/blob/main/examples/custom_server_middleware/pubspec.yaml 
https://github.com/schultek/jaspr/blob/main/examples/dart_frog_backend/pubspec.yaml
https://github.com/schultek/jaspr/blob/main/examples/riverpod_app/pubspec.yaml
https://github.com/schultek/jaspr/blob/main/examples/shelf_backend/pubspec.yaml

It might be worth considering using relative imports for the packages in this repository and creating a github action which makes sure that all examples remain executable.

**Expected Behavior**

Examples work with the most recent version of jaspr.

**Additional Context**

It might also be worth thinking about moving the examples into the respective packages, to have an "example" for the pub.dev pages for the packages.

**Comment by schultek** [comment]
I think there are two todos here:

1. Improve the documentation of the examples.
2. Make sure the examples are updated **and stay updated and working** by integrating something in the ci release workflow.

**Comment by schultek** [comment]
Hi, I will close this as these are improved by now and I don't have any concrete todos here right now. Feel free to reopen this or another issue if you have any more specific improvement ideas.
