### ISSUE TITLE
Suggestion: use standard Dart formatting

### ISSUE THREAD

**Issue by fusion44** [schultek/jaspr#136]
Every time I change something in the Jaspr codebase, the Dart formatter changes large parts of the source code. This makes contributing quite difficult. It would be great if the Jaspr codebase could be reformatted using Dart's default settings.

For example, the maximum line length is violated in quite a few places. 

@schultek, I can open a PR about this, if agreed.

**Comment by schultek** [comment]
It uses formatting, but on 120 line length currently.
