### ISSUE TITLE
Router: some missing features - feedback

### ISSUE THREAD

**Issue by daniel-v** [schultek/jaspr#14]
Hello there!

I'm looking into jaspr for a couple of hobby projects. I ran into an issue with Router. It is mentioned on wiki that it is WIP so I thought I might still be in time to provide some feedback.

1. First thing I noticed is that you there is no option to specify custom location strategies. Currently only path is considered. Which means I cannot easily "point to" tabs on a specific page. Something like `/my-awesome-page?tabbed-view=5-star`.
2. `_ResolvedRoute` is library private and therefore I cannot easily implement custom Route implementations either, nor can I extend `ResolvedRoute` since  it is effectively sealed with default forwarding factory constructor.

Ultimately, I think my pain point is that I cannot customize routing which is quite restrictive. Even `onGenerateRoute` receives only the path. I think passing an `URI` to it would open up quite a few possibilities with minor code change. I could implement my custom routing logic.

Cheers!

**Comment by nimr77** [comment]
Hi have you tried 
https://pub.dev/packages/jaspr_router

**Comment by schultek** [comment]
Closing this since the router package has been rewritten from ground up.
