### ISSUE TITLE
feat: Add template specific for SSG

### ISSUE THREAD

**Issue by cybertheory** [schultek/jaspr#145]
**Description**

I used the fully client-side template for my ssg (static site generation). I am just learning jaspr by redoing my site. However, the CLI command 'jaspr generate' doesn't seem to be picking up the main.dart file it doesn't seem to be in the right place.  I think it would be better to have an SSG template and the SSG commands so it works together well. I am sure a lot of people who are building websites will be making static websites instead of data-powered sites.

**Additional Context**

**Comment by cybertheory** [comment]
Would be willing to work on this, where is the cli package source code?

**Comment by fusion44** [comment]
All the packages are in the packages folder: https://github.com/schultek/jaspr/tree/main/packages/jaspr_cli
