### ISSUE TITLE
Jaspr Community on Discord

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#15]
Hello @schultek, @snehmehta and others,
For better communication during contributing I created Discord server here: https://discord.gg/G8pH8X4u
Where you can join and we can communicate on next progress. ;-)

**Comment by schultek** [comment]
Hi @mjablecnik, great idea! Can you send a new link, the current one is expired.

**Comment by gamelaster** [comment]
@schultek https://discord.gg/yuBS8jPP3K

**Comment by schultek** [comment]
This is now linked in the readme
