### ISSUE TITLE
Platform Imports are not working

### ISSUE THREAD

**Issue by cybertheory** [schultek/jaspr#152]
**Description**

Tried to import dart:html with platform imports from the examples of the docs and they are not working.
![image](https://github.com/schultek/jaspr/assets/27149047/28e155c2-09fa-418f-9856-f838cc23b7f3)
![Screenshot 2024-01-09 at 8 38 14 PM](https://github.com/schultek/jaspr/assets/27149047/74553d29-c5c9-4e3a-af19-158b455ae7a5)

**Steps To Reproduce**

1. Activate jaspr through `dart pub global activate jaspr_cli`
2. Create a new project with `jaspr create -t ... my_app`
3. Use conditional imports to import window from dart:html as per documentation

**Expected Behavior**

should import and build, and autogen imports.dart

**Additional Context**

**Comment by schultek** [comment]
The `.imports.dart` file is first generated when you run `jaspr serve`.

**Comment by cybertheory** [comment]
Interesting anyway to do this when we create the jaspr project? And just add to it?

**Comment by cybertheory** [comment]
yeah just kept on going :(

**Comment by schultek** [comment]
Closing this as I think its solved by now. Feel free to reopen if you still have problems.

**Comment by walsha2** [comment]
@cybertheory did you ever get this to work?
