### ISSUE TITLE
Dom events not working 

### ISSUE THREAD

**Issue by ingego** [schultek/jaspr#170]
Hi mans, doom events is not worked, please, check this code 

```
class InheritedCount extends InheritedComponent {
  InheritedCount(this.count, {required Component child}) : super(child: child);

  final int count;

  @override
  bool updateShouldNotify(covariant InheritedCount oldComponent) {
    return count != oldComponent.count;
  }
}

class App extends StatefulComponent {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  int count = 0;

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield InheritedCount(
      count,
      child: CountLabel(),
    );

    yield DomComponent(
      tag: 'button',
      id: "sdf",
      events: {
        'click': (e) {
          print("sdfsdf");
          setState(() => count++);
        },
      },
      child: Text('Press Me'),
    );
  }
}

class CountLabel extends StatelessComponent {
  const CountLabel({Key? key}) : super(key: key);

  @override
  Iterable<Component> build(BuildContext context) sync* {
    var count =
        context.dependOnInheritedComponentOfExactType<InheritedCount>()!.count;
    yield Text('Count is $count');
  }
}

```
run jaspr serve 
and this  
https://github.com/schultek/jaspr/assets/26673298/246a4e87-c99b-4f30-99ed-02529086cc67

meta: 
[✓] Jaspr CLI (Version 0.10.0)
  • Dart Version 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "macos_arm64" at dart
  • Running on macos Version 14.1.1 (Build 23B81) - Locale ru-RU
  • Analytics: Enabled

[✓] Current Project
  • Dependencies on core packages:
    • jaspr: ^0.10.0
    • jaspr_builder: ^0.10.0 (dev)
  • Uses server-side rendering: true
  • Uses experimental compilers: false
  • Uses flutter embedding: false

**Comment by ingego** [comment]
try : 
  jaspr clean 
  jaspr build (and start prod server) 
  change browse 

work on macos

**Comment by ingego** [comment]
try 
    yield DomComponent(
      tag: 'button',
      id: "sdf",
      events: events(onClick: () {
        print("click");
      }),
      child: Text('Press Me'),
    );
    
    not working

**Comment by ingego** [comment]
why, i'am think, is not working? 


[SERVER] The Dart VM service is listening on http://127.0.0.1:8181/qksvtipkIrE=/
[SERVER] The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/qksvtipkIrE=/devtools?uri=ws://127.0.0.1:8181/qksvtipkIrE=/ws
[SERVER] [WARNING] Jaspr was not initialized. Call Jaspr.initializeApp() before calling runApp(). This will be required in a future version of jaspr and result in an error.
[SERVER] [INFO] Server hot reload is enabled.
[SERVER] [INFO] Running app in debug mode
[SERVER] [INFO] Serving at http://localhost:8080

terminal not show message "click"

**Comment by ingego** [comment]
UDP 


      await tester.click(find.tag('button').first); // it's worked 
      
      but, in browse not worked

**Comment by ingego** [comment]
upd 
try to jaspr generate 
 -> get this error [CLI] [ERROR] FailureType: 73
 
 and get this html file 

``` 
<!DOCTYPE html>
<p>Count is 0</p>
<button id="sdf">Press Me</button>
<button>sdfsdf</button>

```

**Comment by ingego** [comment]
<img width="230" alt="Снимок экрана 2024-02-06 в 08 53 45" src="https://github.com/schultek/jaspr/assets/26673298/adf4df35-2415-4621-8975-cad0b83f7db5">
test.dart.js not found

**Comment by ingego** [comment]
hi, run command 
[BUILDER] Connecting to the build daemon...
[BUILDER] Generating build script...
[BUILDER] Generating build script completed, took 163ms
[BUILDER] Starting daemon...
[BUILDER] Initializing inputs
[BUILDER] Reading cached asset graph...
[BUILDER] Reading cached asset graph completed, took 131ms
[BUILDER] Checking for updates since last build...
[BUILDER] Checking for updates since last build completed, took 451ms
[BUILDER] Initializing inputs
[BUILDER] Reading cached asset graph...
[BUILDER] Reading cached asset graph completed, took 131ms
[BUILDER] Checking for updates since last build...
[BUILDER] Checking for updates since last build completed, took 451ms
[BUILDER] Setting up file watchers...
[BUILDER] Setting up file watchers completed, took 2ms
[BUILDER] Registering build targets...
[BUILDER] Starting initial build...
[BUILDER] Starting resource servers...
[CLI] Starting web builder...
[BUILDER] About to build [web]...
[BUILDER] Running build...
[CLI] Building web assets...
[BUILDER] Running build completed, took 72ms
[BUILDER] Caching finalized dependency graph...
[BUILDER] Caching finalized dependency graph completed, took 117ms
[BUILDER] Succeeded after 193ms with 0 outputs (0 actions)
[BUILDER] --------------------------------------------------------------------------------------------------------------------------------------------------------------------
[CLI] Done building web assets.
[CLI] Starting server...
[CLI] Server started.
[SERVER] The Dart VM service is listening on http://127.0.0.1:8181/SoHxDBdATEk=/
[SERVER] The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/SoHxDBdATEk=/devtools?uri=ws://127.0.0.1:8181/SoHxDBdATEk=/ws
[SERVER] [WARNING] Jaspr was not initialized. Call Jaspr.initializeApp() before calling runApp(). This will be required in a future version of jaspr and result in an error.
[SERVER] [INFO] Server hot reload is enabled.
[SERVER] [INFO] Running app in debug mode
[SERVER] [INFO] Serving at http://localhost:8080


----- after click -----
nothing

**Comment by schultek** [comment]
Are you missing the `@client` annotation on the App component?

**Comment by ingego** [comment]
add annotation, but not working

**Comment by schultek** [comment]
Can you create a new project with the basic template and see where the setup is different.

**Comment by ingego** [comment]
окей, jaspr create ?

**Comment by ingego** [comment]
<img width="724" alt="Снимок экрана 2024-02-09 в 02 57 15" src="https://github.com/schultek/jaspr/assets/26673298/53f581b3-1233-48f2-b9a4-9be3619e9ef3">
 --create app

<img width="432" alt="Снимок экрана 2024-02-09 в 02 58 33" src="https://github.com/schultek/jaspr/assets/26673298/c47ae880-786f-434b-b0d4-a7bac6df0ea3">
-- add button 

<img width="930" alt="Снимок экрана 2024-02-09 в 02 59 42" src="https://github.com/schultek/jaspr/assets/26673298/a720f841-8ad2-4128-83f7-88493f418842">

--run jaspr serve 


<img width="313" alt="Снимок экрана 2024-02-09 в 03 00 31" src="https://github.com/schultek/jaspr/assets/26673298/a823cd0c-191c-4122-87be-13e4d081585f">

--button event not working

**Comment by ingego** [comment]
this new project 
[project](https://drive.google.com/file/d/1FXnSTz0Wd787IIWl868CoN6LOyucB8hl/view?usp=sharing)

**Comment by schultek** [comment]
> this new project [project](https://drive.google.com/file/d/1FXnSTz0Wd787IIWl868CoN6LOyucB8hl/view?usp=sharing)

I downloaded this and it works fine.

**Comment by schultek** [comment]
Ahh wait: You need to check the browser console for client logs. The terminal process currently does not stream client logs.

**Comment by ingego** [comment]
okay, logs is working on browse in project 1 app. 
Now, can you view project two ? (with button and state changes)
[project two](https://drive.google.com/file/d/16FoGkgyEMDOhQMVuHQfr_a4cr4rPTXPb/view?usp=sharing)

**Comment by ingego** [comment]
mb, how to restart all jaspr framework ? mb delete all jaspr & jaspr_cli?

**Comment by schultek** [comment]
I recommend you join the discord server, you can ask questions to the community and there is also a code-review channel.
