### ISSUE TITLE
Failed to initialize incremental compiler

### ISSUE THREAD

**Issue by codekeyz** [schultek/jaspr#178]
**Description**

<img width="1290" alt="Screenshot 2024-03-02 at 9 26 20 PM" src="https://github.com/schultek/jaspr/assets/22515508/a3f59e74-ae10-48c0-b2d7-69f46e871049">

```
[BUILDER] [ERROR] #9      main (file:///Volumes/Work/s/w/ir/x/w/sdk/utils/bazel/kernel_worker.dart:30:5)
[BUILDER] [ERROR] <asynchronous suspension>
[BUILDER] [ERROR] AssetNotFoundException: meta|lib/meta_meta.ddc.dill
[BUILDER] [ERROR] AssetNotFoundException: meta|lib/meta_meta.ddc.dill
[BUILDER] [ERROR] AssetNotFoundException: meta|lib/meta_meta.ddc.dill
[BUILDER] [ERROR] AssetNotFoundException: meta|lib/meta_meta.ddc.dill
[BUILDER] [ERROR] AssetNotFoundException: web|web/main.clients.bootstrap.ddc.js.metadata
[BUILDER] [ERROR] AssetNotFoundException: web|web/components/app.client.bootstrap.ddc.js.metadata
[BUILDER] [ERROR] Failed after 1.0s
[CLI] [ERROR] Failed building web assets. There is probably more output above.
⠹ [CLI] Building web assets... (This takes longer for the initial build)... (28.9s)
```

**Steps To Reproduce**

1. Activate jaspr through `dart pub global activate jaspr_cli`
2. Create a new project with `jaspr create`, choose recommended
3. Run `jaspr serve`

**Expected Behavior**

**Additional Context**

I'm not really sure what's happening. I just run `jaspr create` and used the recommended template. Then i run `jaspr serve` and then i had this.

Dart Version
```
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"
```

**Comment by schultek** [comment]
Whats the output of 'jaspr doctor'?

**Comment by schultek** [comment]
Some general things you can try:

jaspr clean
dart pub upgrade
using build_web_compilers instead of if you selected jaspr_web_compilers

Let me know if any of those helped.

**Comment by codekeyz** [comment]
Okay, let me try that.

**Comment by schultek** [comment]
Closing as stale.
