### ISSUE TITLE
feat: Update gitignore when using jaspr create

### ISSUE THREAD

**Issue by walsha2** [schultek/jaspr#188]
**Description**

The following should be added to `.gitignore` when using `jaspr create`. 

```.gitignore
# Files and directories created by flutter.
.flutter-plugins
.flutter-plugins-dependencies
```

**Additional Context**

When adding `flutter` packages that are going to be used through interop in a `jaspr` app, these files can get created and they should get ignored  - as they would for a conventional flutter project.

For reference, here is the `flutter` `.gitignore` template. It might be worthwhile to expand the `jaspr` template `.gitignore`, it is pretty sparse right now?

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app_shared/.gitignore.tmpl

**Comment by schultek** [comment]
This is part of #168
