### ISSUE TITLE
rect component should not require "x" and "y" attributes

### ISSUE THREAD

**Issue by walsha2** [schultek/jaspr#189]
**Description**

The following is an entirely valid `rect` component per HTML spec:

```html
<rect width="100" height="100" />
```

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect

-----------

However, the `jaspr` prebuilt `rect` component requires `x` and `y` to be defined as non-nullable strings. Not sure why these need to be required?

**Proposal**

These should be nullable, optional, string inputs - just like `width` and `height`

**Comment by schultek** [comment]
True, don't know how that slipped in

**Comment by schultek** [comment]
Fixed in master, will release with the other stuff
