### ISSUE TITLE
No executable on pub bin after global activate jaspr on windows

### ISSUE THREAD

**Issue by SuperPenguin** [schultek/jaspr#2]
I tried activating jaspr global and it seems it doesn't have any executable on my pub bin.
Already tried to deactivate and activate it again, seems no avail. I also tried to activate other package for example [rename](https://pub.dev/packages/rename) without no issue at all.

However running
```
dart pub global run jaspr --help
```
seems to work

https://user-images.githubusercontent.com/1574722/171862828-97a65558-bb39-4e68-9ed4-d8da905f33f0.mp4

**Comment by schultek** [comment]
Fixed in `v0.1.2`
