### ISSUE TITLE
Problem with update dependencies

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#20]
@schultek I see you updated version jaspr to 0.2.0 today and I pull changes from main into my local branch but now after run `dart pub get` I get this error:
```
Resolving dependencies...
Because jaspr depends on jaspr_test ^0.1.0 which depends on jaspr ^0.1.0, jaspr ^0.1.0 is required.
So, because jaspr is 0.2.0, version solving failed.
Process finished with exit code 1
```
![image](https://user-images.githubusercontent.com/2686906/179095069-c54f8a73-b13a-4bdd-bd7d-fcb649125dc3.png)

Can you fix it please?

**Comment by schultek** [comment]
For local development activate `melos` and run `melos bootstrap`. This should link all local packages instead of taking the versions from pub.
