### ISSUE TITLE
fix: Jaspr-Tailwind fail on Windows

### ISSUE THREAD

**Issue by carmas123** [schultek/jaspr#206]
**Description**

Has explained here: [https://github.com/dart-lang/sdk/issues/50076]
running a process under Windows with custom args can fail with spaces or other custom chars.
In [https://github.com/schultek/jaspr/tree/main/packages/jaspr_tailwind] JasperTailwind we run the process using the `--content` arg and `{lib,web}` this fail on Windows that does not accept this sintax.

To solve this we need to quote the content param value.

**Comment by dhafinrayhan** [comment]
Probably related to these:
https://github.com/dart-lang/sdk/issues/42571
https://github.com/dart-lang/sdk/issues/50076

**Comment by schultek** [comment]
This is merged
