### ISSUE TITLE
Add documentation comments for public classes and methods

### ISSUE THREAD

**Issue by suragch** [schultek/jaspr#233]
**Description**

The [website documentation](https://docs.page/schultek/jaspr) is pretty good. It would also be helpful to have documentation comments for the various public classes and methods in Jaspr. It appears that currently none of the code has doc comments.

**Additional Context**

I'm familiar with Flutter but not so much with CSS. A lot of the syntax follows HTML and CSS naming conventions, but for someone not familiar with these things, it's a little difficult to understand how styling and other aspects work when reading and exploring the code. For example, what is a `flexbox` or `rem` or `div` or `section`? I'm sure they make sense to someone from a web dev background but not so much for a Flutter dev. And if I had a web dev background in the first place, I probably wouldn't need to use Jaspr.

If I continue using Jaspr, I might be willing to add documentation comments as I learn what things do. Are you open to PRs for that?

**Comment by schultek** [comment]
Yes code docs are behind big time 🙈 These really need some love.

PRs would be awesome!

**Comment by suragch** [comment]
Sorry, I was wrong about none of code having doc comments. I had missed it earlier by not scrolling down far enough in VS Code's documentation preview. However, I did submit PR #234 to add comments for the CSS units that had previously confused me.
