### ISSUE TITLE
docs(jaspr_router): Make it clear what type of data can be passed to the `extra` parameter

### ISSUE THREAD

**Issue by Maksimka101** [schultek/jaspr#240]
I've tried to push a route with a non primitive data in the `extra` parameter and got the error `UnimplementedError: structured clone of other type`. I figured out that `Router.push` method is using the `window.history.pushState` method and passes my model there which leads to the error above

It would be nice to mention that the `extra` parameter has some restrictions

Ps. I've fixed the error by serializing my model to json string and passing this string to the `extra` parameter

**Comment by schultek** [comment]
This is added to the code comments and documentation now.
https://docs.page/schultek/jaspr/components/router#using-extra
