### ISSUE TITLE
feat: Attributes at the <html> tag level

### ISSUE THREAD

**Issue by dinko7** [schultek/jaspr#241]
**Description**

In my current setup, I'm only using `Document.template` with an `index.html` because there's currently no way to set attributes at `<html>` level. Here's what I'd want to have as an output:

`<html data-theme="dark">`.

A good solution would be to be able to provide a `Map`, similar to how `Styles.raw` allows for any attribute to be added to most Components. That way, anybody could manipulate these properties. A simple use case for this is changing the `data-theme` from `dark` to `light`.

**Comment by schultek** [comment]
This is only for ssr, or do you want to change this value during client rendering?

**Comment by schultek** [comment]
This is included in the newest version as `Document.html(attributes: {...})`. See https://docs.page/schultek/jaspr/components/document#documenthtml
