### ISSUE TITLE
Missing files and folders when deploying to Google Cloud Run

### ISSUE THREAD

**Issue by alexrabin** [schultek/jaspr#257]
**Description**

First off, thank you so much for creating Jaspr!

Now to the issue...

I created a [Jaspr Test Project](https://github.com/alexrabin/JasprTest) and want to deploy on Google Cloud Run.

[Here](https://jasprtest-mhtd3hm25a-uw.a.run.app) is the deployed app. 

As you can see not all of the javascript files, image assets, and styles are included in this bundle.

When I build the following docker file on my local machine, the project runs perfectly, all the assets are included in the docker image, but when the project is built on Google Cloud Build not all the files are copied over.

```Dockerfile

FROM ghcr.io/cirruslabs/flutter:stable AS build

RUN touch /.dockerenv

# Setup Tailwind CSS
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

# Resolve app dependencies.
WORKDIR /app
COPY . .


RUN rm -f pubspec_overrides.yaml

# Must build the app as a non root user.
RUN useradd -ms /bin/bash developer

RUN chown -R developer:developer /usr/local/bin
RUN chmod 755 /usr/local/bin
RUN chown -R developer:developer /app
RUN chmod 755 /app

RUN chown -R developer:developer /sdks/flutter
RUN chmod 755 /sdks/flutter

USER developer

# Must run flutter doctor to download the web sdk.
RUN flutter doctor -v

RUN dart pub get
RUN dart pub global activate jaspr_cli

# Build project
RUN dart pub global run jaspr_cli:jaspr build --verbose

# This is additionally needed for the runtime libs.
FROM dart:stable AS dart

FROM scratch

COPY --from=dart /runtime/ /
COPY --from=build /app/build/jaspr/ /app/

WORKDIR /app

# Start server.
EXPOSE 8080
CMD ["./app"]

```

As I was constructing this Dockerfile I took inspiration from a couple of the jaspr app examples in this repo and [this jaspr project with Tailwind](https://github.com/siesdart/jaspr-portfolio/blob/main/Dockerfile).

As you can see, I had to run the flutter commands as a different user in the Dockerfile. When I used only the root user, I got errors from the flutter command that I shouldn't run flutter as root and then the build would crash.

**Steps To Reproduce**

1. Make a fork of the project https://github.com/alexrabin/JasprTest
2. Make a google cloud project at https://console.cloud.google.com
3. Navigate to Google Cloud Run
4. Create Service
5. Continuously deploy from a repo
6. Set up with cloud build
7. Select the source repo 
8. Select Dockerfile for build type and save
9. Press create 
10. Wait for build to complete and then observe missing files.

**Expected Behavior**

The docker image should contain all files from the jaspr build command.

**Comment by schultek** [comment]
> When I build the following docker file on my local machine, the project runs perfectly, all the assets are included in the docker image, but when the project is built on Google Cloud Build not all the files are copied over.

Since it runs locally this is probably a configuration of cloud run that causes this. I don't think this is an issue caused by jaspr, nor do I have enough information to suggest a solution, sry.

**Comment by alexrabin** [comment]
@schultek i saw that a couple of the example projects in this report use google cloud run, did you have to do anything special to deploy those projects in order for the apps to run correctly?

**Comment by schultek** [comment]
Nothing special.

Although I do build the docker container locally and not in cloud build.

I'd suggest you join Discord and ask for help there, I know a couple of people there who have used docker with jaspr before.

**Comment by alexrabin** [comment]
Since I was using tailwind and [material tailwind](https://www.material-tailwind.com) I needed to run npm install. 

I added the following section into the docker file and then all the files were generated correctly:

```Dockerfile
ENV NODE_VERSION=20.13.1
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

RUN npm i

COPY . .

```

Here is the full Dockerfile that worked for me:

```Dockerfile

FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app
COPY . .

ENV NODE_VERSION=20.13.1
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

RUN npm i

COPY . .

# Setup Tailwind CSS
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

# Resolve app dependencies.
RUN rm -f pubspec_overrides.yaml

# Must build the app as a non root user.
RUN useradd -ms /bin/bash developer

RUN chown -R developer:developer /usr/local/bin
RUN chmod 755 /usr/local/bin
RUN chown -R developer:developer /app
RUN chmod 755 /app

RUN chown -R developer:developer /sdks/flutter
RUN chmod 755 /sdks/flutter

USER developer

# Must run flutter doctor to download the web sdk.
RUN flutter doctor -v

RUN dart pub get
RUN dart pub global activate jaspr_cli

# Build project
RUN dart pub global run jaspr_cli:jaspr build --verbose

# This is additionally needed for the runtime libs.
FROM dart:stable AS dart

FROM scratch

COPY --from=dart /runtime/ /
COPY --from=build /app/build/jaspr/ /app/

WORKDIR /app

# Start server.
EXPOSE 8080
CMD ["./app"]

```
