### ISSUE TITLE
fix: @encoder / @decoder customization error

### ISSUE THREAD

**Issue by siesdart** [schultek/jaspr#270]
**Description**

I defined a custom override as [documented](https://docs.page/schultek/jaspr/utils/at_encoder_decoder#customize-serialization-of-third-party-types) to implement custom serialization. However, when I run it, I found that `model_override.dart` is not imported into `jaspr_options.dart`. I think it is needed to fix to import the file where the custom override is defined in order to run it.

**Steps To Reproduce**

1. Download the [fluttercon](https://github.com/schultek/jaspr/tree/main/apps/fluttercon) app.
2. Upgrade all packages to the latest version.
3. Serve the app.
4. See the error, `Error: Method not found: 'SessionCodex'.`

**Doctor Output**

```
[✓] Jaspr CLI (Version 0.14.0)
  • Dart Version 3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on "macos_arm64" at /opt/homebrew/Caskroom/flutter/3.24.0/flutter/bin/cache/dart-sdk/bin/dart
  • Running on macos Version 14.5 (Build 23F79) - Locale ko-KR
  • Analytics: Enabled

[✓] Current Project
  • Dependencies on core packages:
    • jaspr: ^0.14.0
    • jaspr_builder: ^0.14.0 (dev)
    • jaspr_web_compilers: ^4.0.9 (dev)
    • jaspr_router: ^0.5.0
  • Rendering mode: static
  • Uses jaspr compilers: true
  • Uses flutter embedding: false
```

**Expected Behavior**

The custom override should be imported and find the methods normally.

**Additional Context**

This is a different issue: I'm using `melos` to structure my project. Until the previous version, it would detect `@encoder / @decoder` in other packages as well and generate `jaspr_options.dart`. However, after upgrading, I found that it no longer detects annotations in other packages than the Jaspr app. (In fact, this issue was discovered after I tried to do a custom override in the app project because of this.) If this is an unintended consequence, I'd like to hear your thoughts on it. Thanks.

**Comment by schultek** [comment]
Fixed in 0.15.0. Also supports multi packages now.
