### ISSUE TITLE
feat: hability to the get the current device size

### ISSUE THREAD

**Issue by pedromassango** [schultek/jaspr#272]
**Description**

Hability to get the current screen size would be great to build variations of the app based on breakpoints.

**Additional Context**

Building a simple lading page, I want to be able to build for just to screen sizes, if current-size <600 everything in vertical, hotherwise render horizontally

**Comment by schultek** [comment]
You should use `css.media()` to define a media css rule.

https://docs.page/schultek/jaspr/utils/at_css#special-style-rules
https://developer.mozilla.org/en-US/docs/Web/CSS/@media
