### ISSUE TITLE
Change styles dynamically

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#275]
Hello, I am experimenting with Jaspr again and I would like to know how can I change some class or styles in Jaspr dynamicaly based on state.
I am trying this in default demo but it cannot work because styles require only constants:

![Screenshot 2024-08-19 at 14 01 55](https://github.com/user-attachments/assets/4a32ad78-c714-45ac-8f11-8c8e25d20392)

And this also doesn't work:

![Screenshot 2024-08-19 at 14 06 44](https://github.com/user-attachments/assets/fbbdfa87-e6f4-41d2-8d26-078576e7abc8)

**Comment by mjablecnik** [comment]
Ok, thank you. After remove `const` it works.

An I also tried your recommendation with classes:
![Screenshot 2024-08-19 at 22 32 56](https://github.com/user-attachments/assets/79921451-02c7-4cdd-928e-4a783a26cc48)

Thank you very much :)

I have only last question: Why `classes` parameter is `String?` instead of `List<String>?` when it is list of classes?
Is there some special purpose?

**Comment by schultek** [comment]
Mainly because it formats nicer. Previously it was a list but that was messing up the formatting. Also it was doing list.join(' ') anyways internally so a String was the better choice.
