### ISSUE TITLE
Responsive page example

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#277]
Hello,
can I find a tutorial somewhere on how to create responsive components or pages in Jaspr?
I didn't find anything about it in the documentation, but I see that my previous issue has been marked as completed: https://github.com/schultek/jaspr/issues/82

Could you give me a small example of how to do it with CSS in Jaspr?

**Comment by schultek** [comment]
There is `css.media(MediaQuery.screen(minWidth: 200.px), [ ... ])`.
Its briefly mentioned here: https://docs.page/schultek/jaspr/utils/at_css#special-style-rules

But it makes sense to highlight this better in the docs. I will keep this issue open to add a section here: https://docs.page/schultek/jaspr/concepts/styling

**Comment by schultek** [comment]
https://staging.docs.page/schultek/jaspr/concepts/styling#responsive-styles
