### ISSUE TITLE
Border doesn't work

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#278]
Hello, 
I am experimenting with Jaspr and I want to create simple box with border.

Here is small video:

https://streamable.com/bsad1r

But it doesn't work.

And also this code doesn't work for me. 
![Screenshot 2024-08-20 at 16 15 25](https://github.com/user-attachments/assets/dcff2f39-2f6a-4d76-b844-8bb0b27e6087)

Am I doing something wrong?

```
martin at Martins-MacBook-Air my_website >>> jaspr doctor
[✓] Jaspr CLI (Version 0.14.0)
  • Dart Version 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "macos_arm64" at /Users/martin/fvm/versions/3.22.0/bin/cache/dart-sdk/bin/dart
  • Running on macos Version 14.1 (Build 23B74) - Locale en-CZ
  • Analytics: Enabled

[✓] Current Project
  • Dependencies on core packages:
    • jaspr: ^0.14.0
    • jaspr_builder: ^0.14.0 (dev)
    • jaspr_web_compilers: ^4.0.10 (dev)
    • jaspr_router: ^0.5.0
  • Rendering mode: server
  • Uses jaspr compilers: true
  • Uses flutter embedding: false
```

**Comment by schultek** [comment]
Set the BorderSide(style: ) to something, e.g. BorderStyle.solid.

There are also BorderSide.solid() and other convenience constructors

**Comment by mjablecnik** [comment]
Yes, I discovered, it works when I add `style: BorderStyle.solid`.
I thing it would be more friendly for beginners when style will be setup by default.
(I have experience with flutter but not with HTML/CSS so much..)

![Screenshot 2024-08-20 at 16 35 54](https://github.com/user-attachments/assets/e99c7591-32ec-4c86-a32b-30b1ef0e04ca)

**Comment by schultek** [comment]
I think solid makes sense as a default value. You want to open a PR?

**Comment by schultek** [comment]
Done
