### ISSUE TITLE
input html element's value is not set when an empty String is used

### ISSUE THREAD

**Issue by juancastillo0** [schultek/jaspr#28]
Hi,

I found that when I pass an empty String as an attribute to an input element, the text is not cleared. The value of the element is not overridden. However, if the value is a non empty String, the input element's value does change. At the moment, I am saving the `dart:html`'s `InputElement` reference to clear and update the value, like a Flutter `TextEditingController`.

Since `dart:html` cannot be used in the backend, the value is dynamic, could this be resolved in some way? maybe by providing a wrapper for common use cases (a typed event perhaps) or a `TextEditingController` like API? Or should users use `universal_html` and cast everything like `(event as html.Event).target as html.InputElement`?

For the wip/v0.2 branch, I was also wondering whether a `void Function(String value) onValueChange` argument in the input component could be used as API, or maybe instead of `String` as argument it could be a specific type (for number or date inputs) or a typed event (with the new value, the `InputElement` and the raw event).

I tried it in the current main and wip/v0.2 branch.

This is related to a discussion in the rad framework https://github.com/erlage/rad/issues/13.

Thanks!

**Comment by schultek** [comment]
Added in ba0b9f0. The `onValueChange` callback will be added later with actual input components coming soon.
