### ISSUE TITLE
Problem with provisioning of my InheritedWidget

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#281]
Hello, I created my custom Inherited Widget for change of my theme in my project:

![Screenshot 2024-08-22 at 17 52 00](https://github.com/user-attachments/assets/53bbddde-21c1-40c9-b7da-88dd22844645)

And added it here:
![Screenshot 2024-08-22 at 17 52 44](https://github.com/user-attachments/assets/8727fdb8-e0b5-4fa7-8640-38de963779d3)

And here:
![Screenshot 2024-08-22 at 17 53 11](https://github.com/user-attachments/assets/f626829a-5a81-4f61-9886-2921a5f3a634)

But when I want to obtain it in my component:
![Screenshot 2024-08-22 at 17 53 43](https://github.com/user-attachments/assets/31b51833-4852-4a8a-bfe5-564c150c24b3)

I gain error output:
![Screenshot 2024-08-22 at 17 54 29](https://github.com/user-attachments/assets/084de2fa-c82e-458a-b476-b627e60891a3)

Here is my error log:
![Screenshot 2024-08-22 at 17 56 31](https://github.com/user-attachments/assets/acc9870f-a9d7-4e3b-abd2-c5695f2041bf)

**Comment by schultek** [comment]
Yes I guess Theme is only server-side rendered but you try to access it also from a client component.

Check the hydration docs, specifically the section about the server vs client gap.

**Comment by schultek** [comment]
Tbh for this use-case (inherited component somewhere up the tree, needs to be accessed further down on the client) I don't have a good solution right now (... but something I'm working on really cool)

Your choices right now are pretty much limited to
a) put the InheritedWidget in a client component or
b) don't access it from the client

**Comment by mjablecnik** [comment]
Ok, so if I understand correctly, I have to provide my inherited widget inside every page or component annotated by @client annotation.
Now when I added my inherited widget into my Home page so it works.

![Screenshot 2024-08-22 at 19 13 12](https://github.com/user-attachments/assets/301d58f9-8d7d-48d2-9ca1-af1eff8e1618)

**Comment by schultek** [comment]
Seems like this is done.
