### ISSUE TITLE
Convert HTML to jaspr component

### ISSUE THREAD

**Issue by agusibrahim** [schultek/jaspr#285]
I just want to share my project that might be useful for you who are using Jaspr. This can convert HTML to Jaspr components. I hope it helps!
https://github.com/agusibrahim/htmltodart_jaspr
online tool can accessed here:
https://agusibrahim.github.io/htmltodart_jaspr

**Comment by schultek** [comment]
Very cool. Better share this on the community discord in the #showcase channel.
