### ISSUE TITLE
Permanently save data

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#299]
Hello, I need save some variable value in my page (for theme and locale) for prevent reset the value after reload of page.
I have saved it in statefulComponent and I would like to somehow permanently save it during update and load after reload page.

I think that I can do this with cookies but I do not know how to save or load it in Jaspr.

Can you give me some example how can I do it?

**Comment by schultek** [comment]
You can either use `document.cookie` for cookies, or `window.localStorage`.

**Comment by schultek** [comment]
For further help I think we continue this better on discord.

**Comment by mjablecnik** [comment]
> You can either use document.cookie for cookies, or window.localStorage.

@schultek Can you show me some example in Jaspr?
