### ISSUE TITLE
How to generate static website?

### ISSUE THREAD

**Issue by lindeer** [schultek/jaspr#32]
Hi schultek, is it appropriate to use jaspr to generate static pages, like hugo or jekyll did? 

Using `StatelessComponent` to build gui, and using dart to do interaction, and data was injected through `InheritageComponent`, and also it could handle raw html for final page generation, e.g. the raw html generated by markdown files. Seems we need **templatize** dart page files?

It would be a marvelous feature if it could be implemented.

**Comment by schultek** [comment]
Static site generation is definitely planned and on the roadmap. But i cannot say when it will be available yet.

**Comment by lindeer** [comment]
> Static site generation is definitely planned and on the roadmap. But i cannot say when it will be available yet.

sooo great!! I can't wait for it, could I have a look at the overview and design idea? hope to give it a favor
