### ISSUE TITLE
fix: Client components only support initializing formal constructor parameters. Failing element: Home.({InvalidType key})

### ISSUE THREAD

**Issue by sgrekhov** [schultek/jaspr#323]
Steps:
1) Create a new project using `jaspr create project_name`. Answer Yes to all questions
2) In the created project create a new component, say `MainForm`
3) Add this new conponent to any place in `Home`

Actual result: My InteljIdea automatically added import in the form `import 'package:project_name/components/main_form.dart';`.  This leads to `Client components only support initializing formal constructor parameters. Failing element: Home.({InvalidType key})` error. As a result build fails to add `prefix3.Home: ClientTarget<prefix3.Home>('pages/home'),` to `jaspr_options.dart` file. 

It's hard to figure out that the reason of the problem is the way how the new component was imported. Change the import to `import '../components/main_form.dart';` fixes the issue. But it'd be nice if biuld will be able to use 'package:..' imports or, at least, gave some hints how to fix the problem.

**Comment by schultek** [comment]
Looks like something is going wrong with `build_runner` picking up flutter types. I will investigate.

Can you also please add your output of `jaspr doctor`.

**Comment by sgrekhov** [comment]
```
>jaspr doctor

[✓] Jaspr CLI (Version 0.16.0)
  • Dart Version 3.7.0-27.0.dev (dev) (Tue Oct 15 17:02:51 2024 -0700) on "windows_x64" at dart
  • Running on windows "Windows 10 Pro" 10.0 (Build 22631) - Locale en-IL
  • Analytics: Enabled

[✓] Current Project
  • Dependencies on core packages:
    • jaspr: ^0.16.0
    • jaspr_builder: ^0.16.0 (dev)
    • jaspr_router: ^0.6.0
  • Rendering mode: static
  • Uses jaspr compilers: false
  • Uses flutter embedding: false
```
More exact steps to reproduce:
1) Run `jaspr create test`
2) Choose static, answer Yes to all questions exept ones about Flutter.
3) `cd test`
4) `jaspr serve`
5) In `test/lib/pages/home.dart ` replace `import '../components/counter.dart';` to `import 'package:test/components/counter.dart';`
6) Go to `counter.dart` and do any change (replace `text('-')` by `text('--')`, for example.

Result: `[BUILDER] [ERROR] Client components only support initializing formal constructor parameters. Failing element: Home.({InvalidType key})` occurs.

**Comment by schultek** [comment]
I cannot reproduce this.

**Comment by sgrekhov** [comment]
> More exact steps to reproduce:
> 
> Run jaspr create test
> Choose static, answer Yes to all questions exept ones about Flutter.
> cd test
> jaspr serve
> In test/lib/pages/home.dart  replace import '../components/counter.dart'; to import 'package:test/components/counter.dart';
> Go to counter.dart and do any change (replace text('-') by text('--'), for example.
> Result: [BUILDER] [ERROR] Client components only support initializing formal constructor parameters. Failing element: Home.({InvalidType key}) occurs.

Did you try the steps above?

**Comment by schultek** [comment]
Yes followed them exactly. Also tried with different options. On windows and mac.

**Comment by schultek** [comment]
How is your dart and flutter sdk installed?

**Comment by sgrekhov** [comment]
I can't reproduce it as well now, after upgrading the SDK. Closing the issue for now. Sorry for your time.
