### ISSUE TITLE
fix: Getting `Error on building component: Bad state: No ProviderScope found`

### ISSUE THREAD

**Issue by rubiktubik** [schultek/jaspr#326]
**Description**

I have created a new jaspr server project using the custom shelf server option and getting the following error:

```bash
Error on building component: Bad state: No ProviderScope found
```

Probably i'am using ProviderScope wrong in this constelation. Or its a bug :-)

**Steps To Reproduce**

<img width="868" alt="grafik" src="https://github.com/user-attachments/assets/61f91238-267b-4cd7-ad26-8c7175f0bef7">

- add jaspr_riverpod package with `dart pub add jaspr_riverpod`

- Add a provider to the end of the counter.dart :

```dart
class CounterNotifier extends Notifier<int> {
  @override
  int build() {
    return 0;
  }

  void plus() {
    state++;
  }

  void minus() {
    state--;
  }
}

final counterProvider =
    NotifierProvider<CounterNotifier, int>(CounterNotifier.new);

```

Add the `ProviderScope`

```dart
      body: ProviderScope(
        child: App(),
      ),
```

**Doctor Output**

```shell
• Dart Version 3.5.1 (stable) (Tue Aug 13 21:02:17 2024 +0000) on "macos_arm64" at /Users/myuser/.local/share/mise/installs/flutter/3.24.1-stable/bin/cache/dart-sdk/bin/dart
  • Running on macos Version 14.1.2 (Build 23B92) - Locale de-DE
  • Analytics: Enabled

[✓] Current Project
  • Dependencies on core packages:
    • jaspr: ^0.16.0
    • jaspr_builder: ^0.16.0 (dev)
    • jaspr_web_compilers: ^4.0.10+1 (dev)
    • jaspr_riverpod: ^0.3.15
    • jaspr_router: ^0.6.0
  • Rendering mode: server
  • Uses jaspr compilers: true
  • Uses flutter embedding: false
```

**Expected Behavior**

Counter works and keeps state with provider

**Additional Context**

**Comment by schultek** [comment]
Answered on github. ProviderScope needs to be used on the client as well.
