### ISSUE TITLE
jaspr_riverpod - Using SyncProvider will render the result in the HTML of the site (commented)

### ISSUE THREAD

**Issue by jokilic** [schultek/jaspr#342]
**Description**

When using `SyncProvider` and using it by triggering it in `preloadDependencies`, everything works well, but the result from that `Provider` is visible in the rendered HTML of the site.

**Steps To Reproduce**

1. Trigger a SyncProvider
2. Check HTML in Dev Tools of your browser
3. See commented out result of the provider

**Expected Behavior**

I don't want the result to be in the HTML.

**Additional Context**

Example `SyncProvider`

```
final testSyncProvider = SyncProvider<String>(
  (ref) async {
    await Future.delayed(const Duration(seconds: 3));
    return 'Hello there';
  },
  id: 'TestSyncProvider',
  name: 'TestSyncProvider',
);
```

Screenshot of the rendered HTML is in the attachment.
![Screenshot 2024-11-28 at 12 23 33](https://github.com/user-attachments/assets/43b85279-0260-42a1-9fc0-fed0ff18231b)

**Comment by schultek** [comment]
This is not a bug, its the whole purpose of sync provider.

If you want the data to be available on the client, it has to be sent to the client somehow. And since its during the server side rendering, it will be embedded in the html.

Its the same how @client components or @sync works.

**Comment by schultek** [comment]
If you don't want the data to be synced and only use it on the server, you can use a normal future provider and await it inside an async component.

**Comment by jokilic** [comment]
I understand what you mean.
Nonetheless, I have refactored my code and replaced `SyncProvider` with the Jaspr `AsyncStatelessComponent`.

This one seemed to fit my purposes more better.
When the page is rendered, there's no backend response in the comment of the HTML.

Thank you for your help, you can close the issue if you see fit.
