### ISSUE TITLE
Can the jaspr_flutter_embed package work in static mode?

### ISSUE THREAD

**Issue by DemianKryk** [schultek/jaspr#346]
I successfully used the `jaspr_flutter_embed` package in server mode, where it worked as expected. However, when I tried to use it in static mode(I didn't change any files), it did not function. Specifically, no files or references for the embedded Flutter content were generated in the `index.html` file.

**Comment by schultek** [comment]
It will work, but it will not pre-render, as flutter cannot prerender on the server.
In the static html you will just get the target div and then once opened on the client the flutter app will load.
