### ISSUE TITLE
docs: missing information on what to do when the project depends on flutter when deploying with firebase

### ISSUE THREAD

**Issue by MarkOSullivan94** [schultek/jaspr#348]
**Description**

I have my existing landing page deployed with Firebase: https://cazadecasa.xyz/

However when trying to do a preview build which embeds a demo version of the Flutter app I'm having issues getting a successful build: https://cazadecasa-379e0--embedded-flutter-app-nzeqsomj.web.app/

I noticed there is an additional step for [GitHub Pages](https://docs.page/schultek/jaspr/concepts/deploying#flutter-support) and [Server Hosting](https://docs.page/schultek/jaspr/concepts/deploying#flutter-support-1) which explains what is necessary to get your project to work if there is a dependency on Flutter for element embedding or if it depends on `jaspr_web_compilers` which left me thinking perhaps there's an extra step that is required?

If there is no additional step required then it'd be good to at least update the docs to state no additional step should be required.

Docs: https://docs.page/schultek/jaspr/concepts/deploying#firebase-hosting

**Additional Context**

The project I have is a client Jaspr project.

At first I did think perhaps it was an issue with the preview functionality with Firebase hosting so I checked out the last release version of the landing page and deployed it and it worked fine: https://cazadecasa-379e0--preview-1tuw5ep6.web.app/

**Comment by schultek** [comment]
I don't thing there are other steps needed for firebase.

> However when trying to do a preview build which embeds a demo version of the Flutter app I'm having issues getting a successful build: https://cazadecasa-379e0--embedded-flutter-app-nzeqsomj.web.app/

What are the issues? The page seems to work fine, I see the embedded flutter app.

**Comment by MarkOSullivan94** [comment]
Apologies for opening this! After deploying I thought after waiting a few minutes it wasn't working and because when I deployed the other preview build it appeared faster I thought perhaps there was an issue.
