### ISSUE TITLE
Classic template not working

### ISSUE THREAD

**Issue by MarkOSullivan94** [schultek/jaspr#38]
Using `wip/v0.2` branch, I've created a new Jaspr project using the `classic` template and the Hello World text does not appear.

#### What's shown in the browser

<img width="1705" alt="Screenshot 2022-09-13 at 12 31 39" src="https://user-images.githubusercontent.com/6950843/189809898-7fde2f2e-7b1b-404e-bd3d-87abf1663f56.png">

#### DevTools

<img width="1418" alt="Screenshot 2022-09-13 at 12 31 53" src="https://user-images.githubusercontent.com/6950843/189809973-3ec6282e-6591-43ff-8e52-cdfd494f4637.png">

**Comment by schultek** [comment]
Seems to work right now on develop.
