### ISSUE TITLE
Jaspr version confusing

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#63]
Hello, I see that latest Jaspr release is:
![image](https://user-images.githubusercontent.com/2686906/229520600-2699901a-2709-4564-8d55-9badd6d4768c.png)

But when I run:
```
dart pub global activate jaspr_cli
```
and then:
```
jaspr --version
```
I see 
![image](https://user-images.githubusercontent.com/2686906/229520959-1e9f4e44-8dc7-4f2f-beab-ac6f921c0e39.png)

And in my generated project is:
![image](https://user-images.githubusercontent.com/2686906/229521101-7b43f030-0bd7-44ff-8917-aa7b51d27ace.png)

It is very confusing what version now I am using..
Don't should be everywhere latest version: `0.3.0`?

**Comment by schultek** [comment]
The 0.1.0 is the version of the cli package, not the jaspr version that is used in the template.

The used jaspr version is also hardcoded and not yet using the latest from pub automatically.

I see that this is confusing and this needs to be improved.

**Comment by MarkOSullivan94** [comment]
This confused me as well so a +1 from me
