### ISSUE TITLE
Hotreload doesn't work for main.dart file

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#64]
For basic Jaspr project hotreload works for `app.dart` 
but when I change anything in `main.dart` so hotreload doesn't work and I have to run `jaspr serve` again and reload page in browser manually.

**Comment by schultek** [comment]
Yes that is currently expected and a result of the implementation. I havend found a way around that yet.

Currently on hotreload, only the root component is rebuilt, but not the main function recalled.
