### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#65]
Hello, I see that CHANGELOG file is inside every package.
Why can't be only one CHANGELOG in the root of project in one file for better overview about news?

Here is changelog of project where it works: https://github.com/godotengine/godot/blob/master/CHANGELOG.md

**Comment by mjablecnik** [comment]
Why should be it versioned independent? I think, it is also important part of Jaspr or not?

**Comment by mjablecnik** [comment]
And what about automatize it somehow?

**Comment by schultek** [comment]
Still there shouldn't be a new version of the core package when nothing changed.

But generally I'm thinking about ways to automate the release process. While I don't like the semantic commits approach I find this really interesting: https://github.com/rrousselGit/semantic_changelog

**Comment by mjablecnik** [comment]
Ok, so now I am thinking about if jaspr_riverpod and jaspr_router are really core features. 
I thought that so because also in Flutter is state management (Inherited widget) and routing.
But if jaspr_riverpod and jaspr_router are not core features and can have a different versions..
so shouldn't it be somewhere else? For example in thirdparty directory? Because in the future somebody 
can create jaspr_provider or jaspr_bloc and don't use jaspr_riverpod for state management.

So it doesn't make sense to have this packages between other core jaspr packages (jaspr_builder, jaspr_test, jaspr_cli, etc.)

**Comment by easazade** [comment]
> Ok, so now I am thinking about if jaspr_riverpod and jaspr_router are really core features. I thought that so because also in Flutter is state management (Inherited widget) and routing. But if jaspr_riverpod and jaspr_router are not core features and can have a different versions.. so shouldn't it be somewhere else? For example in thirdparty directory? Because in the future somebody can create jaspr_provider or jaspr_bloc and don't use jaspr_riverpod for state management.
> 
> So it doesn't make sense to have this packages between other core jaspr packages (jaspr_builder, jaspr_test, jaspr_cli, etc.)

Makes scenes. I think in react router is built on top of it instead of being built in.
Also looked into remi's `semantic_changelog`. so if that is used for automating the release process and versioning contributor will be responsible to state the semantic version change type? right?

**Comment by schultek** [comment]
> @schultek Also looked into remi's `semantic_changelog`. so if that is used for automating the release process and versioning contributor will be responsible to state the semantic version change type? right?

Yes, each pull request would need to update the changelog, and then the ci will publish a new release after merge.

> So it doesn't make sense to have this packages between other core jaspr packages (jaspr_builder, jaspr_test, jaspr_cli, etc.)

I'm open to rethink the package structure and also sync versions of the core packages (jaspr, jaspr_builder, jaspr_test, jaspr_cli). There needs to be a better version management and publishing process anyways.

**Comment by mjablecnik** [comment]
> and then the ci will publish a new release after merge.

Publishing new release after every merge is too often I think. (if I understand right)
Publishing new release can be one per 1 month or every month with some automatic script if it is possible.

> I'm open to rethink the package structure and also sync versions of the core packages (jaspr, jaspr_builder, jaspr_test, jaspr_cli).

Yes. jaspr, jaspr_builder, jaspr_test, jaspr_cli can be in packages folder as core packages with same version value.
And jaspr_riverpod with jaspr_router can be between thirdparty packages with own versioning..

**Comment by schultek** [comment]
Yes I also would trigger it manually.

We can split the packages, but its not really "thirdparty". Trying to think of a better naming.

**Comment by mjablecnik** [comment]
> We can split the packages, but its not really "thirdparty". I'm trying to think of a better naming.

So what is it? I really don't know how to name it somehow better..

**Comment by schultek** [comment]
Changelog is now shared by the core packages (using symlinks).
I keep them in the same directory for now.
