### ISSUE TITLE
Missing examples linked in docs

### ISSUE THREAD

**Issue by easazade** [schultek/jaspr#71]
Right now two links in [SSR](https://docs.page/schultek/jaspr/core/ssr) docs are pointing to examples that are not there. are they moved?

the link provided for missing server_handling example
https://github.com/schultek/jaspr/tree/main/experiments/server_handling

the link provided for the missing shelf_handler example
https://github.com/schultek/jaspr/tree/main/experiments/shelf_handler

**Comment by schultek** [comment]
Ah they moved to 
https://github.com/schultek/jaspr/tree/main/examples/shelf_backend
and 
https://github.com/schultek/jaspr/tree/main/examples/custom_server_middleware

**Comment by easazade** [comment]
I'll update the doc
