### ISSUE TITLE
Jaspr with Tailwind

### ISSUE THREAD

**Issue by mjablecnik** [schultek/jaspr#79]
**Description**

Hello I experiment with Tailwind in Jaspr and due to Tailwind generator which generate my CSS styles into output file:
![image](https://user-images.githubusercontent.com/2686906/232416998-6a6ae23c-e8bc-412a-9e13-9b0aaf36349c.png)

I have to create build folder by `jaspr build` command and run app with `./build/app`

I would like to use `jaspr serve` command with hot reload for better development but I realize that `jaspr serve`
doesn't create the build folder with javascript sources.

Can you please add this functionality?
For example add a flag `jaspr serve --with-build`?

**Additional Context**

![image](https://user-images.githubusercontent.com/2686906/232418498-1336cf78-4647-4e98-9b85-9b7210157e42.png)

**Comment by schultek** [comment]
`jaspr serve` uses [build_web_compilers](https://pub.dev/packages/build_web_compilers) which in dev mode builds to some temporary directory. I don't know if there is a way to access or change this.
