### ISSUE TITLE
fix: jaspr_router calls onUnknownRoute before navigating to any route

### ISSUE THREAD

**Issue by easazade** [schultek/jaspr#83]
**Description**

I'm using `jaspr_router` and whenever I navigate to another page or whenever a page is loading, the component from onUknownRoute callback is shown. 

**Steps To Reproduce**

```dart
@app
class App extends StatelessComponent with _$App {
  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield Router(
      routes: [
        Route('/', (context) => [HomePage()]),
        Route('/about', (context) => [AboutPage()]),
      ],
      onUnknownRoute: (path, context) => NotFoundPage(),
    );
  }
}

```

https://user-images.githubusercontent.com/38987302/234523761-b4d109a0-f1a3-4598-9fc6-903a1f21ff90.mov

**Comment by schultek** [comment]
Closing this since the router package has been completely rewritten since the issue.
