### ISSUE TITLE
`jaspr create` isn't wokring 

### ISSUE THREAD

**Issue by HosamHasanRamadan** [schultek/jaspr#94]
**Description**
I was trying to create new project with `jaspr create my_app`  then I got this error:
`Could not find pubspec.yaml file. Make sure to run jaspr in your root project directory.`

then I tried to remove pub cache `rm -rf ~/.pub-cache` and activate `jaspr_cli` again nothing changed the same error happened again.

**Steps To Reproduce**
1. Activate jaspr through `dart pub global activate jaspr_cli`
2. Create a new project with `jaspr create  my_app`. 
3. `Could not find pubspec.yaml file. Make sure to run jaspr in your root project directory.`

**Expected Behavior**

project created normally 

**Additional Context**
jaspr cli : 0.6.0
mac os : 13.3 arm64
dart : 3.0.6

**Comment by schultek** [comment]
On it, a little bug that slipped in with the latest release.
